[env:cardputer]
platform  = espressif32
board     = m5stack-stamps3
framework = arduino

; M5Stack Cardputer Adv uses ESP32-S3FN8
board_build.mcu         = esp32s3
board_build.f_cpu       = 240000000L
board_build.flash_mode  = qio
board_build.flash_size  = 8MB
board_build.partitions  = default_8MB.csv

lib_deps =
    https://github.com/m5stack/M5Cardputer.git
    bblanchon/ArduinoJson @ ^7.1
    z3t0/IRremote @ ^4.4

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

monitor_speed = 115200
upload_speed  = 921600
